### ISSUE TITLE
Cancellation Feature Request

### ISSUE THREAD

**Issue by cankarabag** [oneframemobile/networking#11]
The request should have the ability to be canceled with a cancel token. That token should be shared with multiple requests. When a token's cancel method invoked, all requests with this token should be cancelled.

**Comment by emreaktrk** [comment]
Feature added. Please check out documentation about "cancel" 

You can access it on dart_v12_temp branch. Soon merging KS branch.

**Comment by cankarabag** [comment]
Managing the request with the **abort** keyword may not be enough. When a new request has sent after sending a request, the old one should be canceled, but it is necessary to know the old requests that do not constantly return. Could be better way that a cancel token work for multiple requests?
